version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: project_mgmt
    volumes:
      - ../database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - project_network
  
  auth-service:
    image: go-auth-service:v1
    container_name: auth-service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=P@ssw0rd
      - DB_NAME=project_mgmt
      - JWT_KEY=P@ssw0rd
    ports:
      - "3000:3000"
    networks:
      - project_network
    depends_on:
      - db
    restart: unless-stopped

  project-service:
    image: nestjs-project-service:v1
    container_name: project-service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=P@ssw0rd
      - DB_NAME=project_mgmt
      - JWT_KEY=P@ssw0rd
    ports:
      - "3001:3000"
    networks:
      - project_network
    depends_on:
      - auth-service
    restart: unless-stopped   

  task-service:
    build: .
    image: python-task-service:v1
    container_name: task-service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=P@ssw0rd
      - DB_NAME=project_mgmt
      - JWT_KEY=P@ssw0rd
    ports:
      - "3002:3000"
    networks:
      - project_network
    depends_on:
      - project-service
    restart: unless-stopped    

volumes:
  postgres_data:

networks:
  project_network: