version: '3.8'

services:
  # db:
  #   image: postgres:latest
  #   container_name: project_mgmt_db
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: P@ssw0rd
  #     POSTGRES_DB: project_mgmt
  #   volumes:
  #     - ./database/data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - project_network
  
  python-task-service:
    image: python-task-service:v1
    container_name: python-task-service
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=P@ssw0rd
      - DB_NAME=project_mgmt
      - JWT_KEY=P@ssw0rd
    ports:
      - "80:80"
    networks:
      - project_network
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  project_network: